version: '3.9'

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mysql:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=turbin
    command: --default-authentication-plugin=mysql_native_password
    restart: always
  website:
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile
      args:
        BUCKET_NAME: ${BUCKET_NAME}
        IAM_USER_KEY: ${IAM_USER_KEY}
        IAM_USER_SECRET: ${IAM_USER_SECRET}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
